### ISSUE TITLE
Générer un PDF pour chaque document

### ISSUE THREAD

**Issue by IliasRedissi** [Infobourg/docs#3]
Ajouter plusieurs workflows sur GitHub Actions :
- Ajout d'un tag : Générer tous les documents en format PDF et créer une release
- Pull Request : Générer le (ou les) fichier(s) de la PR

Pour générer les fichiers : https://github.com/Infobourg/pandoc-infobourg-template
Commande à utiliser (en fish) : `doker run --rm -u (id -u):(id -g) -v (pwd):/data pandock-infobourg-template -t html --template=infobourg.html -o NOM_DU_DOCUMENT.pdf -s --pdf-engine=weasyprint NOM_DU_DOCUMENT.md`

**Comment by aturlier** [comment]
Si jamais je veux bien être la dessus aussi.

**Comment by IliasRedissi** [comment]
J'ai crée un nouveau repo pour le template : https://github.com/Infobourg/pandoc-infobourg-template

**Comment by aturlier** [comment]
On stocke les PDF où ? En release ?

**Comment by IliasRedissi** [comment]
Je pensais créer un zip avec tous les PDFs pour une release :https://github.com/actions/create-releasehttps://github.com/actions/upload-release-asset Et pour les PR, les laisser dans les artifacts :https://github.com/actions/upload-artifact  De : Axel TurlierEnvoyé le :lundi 4 mai 2020 18:19À : Infobourg/docsCc : Ilias Redissi; AssignObjet :Re: [Infobourg/docs] Générer un PDF pour chaque document (#3) On stocke les PDF où ? En release ?—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by IliasRedissi** [comment]
Je pensais créer un zip avec tous les PDFs pour une release :
- https://github.com/actions/create-release
- https://github.com/actions/upload-release-asset 

Et pour les PR, les laisser dans les artifacts :
- https://github.com/actions/upload-artifact

**Comment by IliasRedissi** [comment]
On peut aussi regarder pour mettre un commentaire dans la PR avec un lien vers le(s) fichier(s) (je sais pas si c'est faisable)
Pour commenter un PR : https://github.com/thollander/actions-comment-pull-request
API pour les artifacts : https://developer.github.com/v3/actions/artifacts/

**Comment by IliasRedissi** [comment]
Il semblerait que ça ne soit pas possible pour le moment car les URLs sont générés après le job et ne sont valides que 1 minute (https://github.com/actions/upload-artifact/issues/62#issuecomment-603778118 et https://github.com/actions/upload-artifact/issues/60#issuecomment-599541847)

**Comment by Milihhard** [comment]
On pourrait pas les stocker en github page?

**Comment by Milihhard** [comment]
Dans ce cas la on ne les génère pas en PDF mais juste en HTML

**Comment by IliasRedissi** [comment]
L'intérêt pour moi de générer un PDF lors d'une PR est de pouvoir rapidement le signer ensuite. La génération lors d'une release est un plus et permet de facilement avoir tous les documents présents à un instant T.

On peut ensuite faire un GitHub Page, mais le but ne sera pas le même : pouvoir accéder plus facilement à la dernière version et mettre en page les documents.

________________________________
De : Milihhard <notifications@github.com>
Envoyé : jeudi 7 mai 2020 à 04:37
À : Infobourg/docs
Cc : Ilias Redissi; Assign
Objet : Re: [Infobourg/docs] Générer un PDF pour chaque document (#3)


Dans ce cas la on ne les génère pas en PDF mais juste en HTML
